# Generated by assistant to add phone_number to Profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_message_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=32, null=True, blank=True),
        ),
    ]
